item {
    name: "Ambulance",
    id: 1,
    display_name: "Ambulance"
}
item {
    name: "Bus",
    id: 2,
    display_name: "Bus"
}
item {
    name: "Car",
    id: 3,
    display_name: "Car"
}
item {
    name: "Motorcycle",
    id: 4,
    display_name: "Motorcycle"
}
item {
    name: "Truck",
    id: 5,
    display_name: "Truck"
}
